"""The one way this project talks to an LLM.

Every text / JSON AI call — card enrichment, conjugation, fun facts, image
prompts, card audits, sentence practice — goes through :class:`AI` and runs
on **Claude via ``claude -p``** (your Claude subscription):

* **One prompt shape**: a shared system preamble plus a task prompt built
  by :mod:`flashcards.tasks` (instruction → context → rules → input JSON).
* **Strict JSON-schema output** (``--json-schema``) for structured tasks;
  plain text otherwise.
* **One cache**: ``ai_cache``, keyed by model + task + messages. Cached
  results are free on re-runs; ``refresh=True`` forces a new answer.
* **Waits instead of failing** when Claude is unavailable (usage limit
  reached, logged out, network down): all AI work pauses, one call retries
  every ``[ai] unavailable_retry_minutes``, and everything resumes when it
  succeeds. Errors specific to one request (invalid output, a timeout) fail
  just that item.
* **Bounded concurrency** (``[ai] concurrency``) however many pipeline
  workers call in, so ``claude -p`` processes never pile up.

Images are generated by Codex on the ChatGPT plan (:mod:`flashcards.codex`),
which shares the same wait-and-retry gate.
"""

from __future__ import annotations

import json
import re
import sqlite3
import subprocess
import tempfile
import threading
from dataclasses import dataclass
from datetime import datetime, timedelta
from typing import Any, Callable, Iterable, Iterator, TypeVar

from .pool import STOP, run_pool
from .settings import settings
from .util import md5_hex

T = TypeVar("T")


class AIError(RuntimeError):
    """This request failed; other requests may still succeed."""


class AIUnavailable(AIError):
    """Claude can't serve anything right now (usage limit, auth, network)."""


@dataclass(frozen=True)
class Task:
    """One AI request. Build these with ``flashcards.tasks`` specs."""

    name: str
    system: str
    prompt: str
    schema: dict | None = None  # None → free-text answer
    timeout: int | None = None
    cache: bool = True

    @property
    def model(self) -> str:
        return settings.ai.model_for(self.name)

    def messages(self) -> list[dict]:
        return [
            {"role": "system", "content": self.system},
            {"role": "user", "content": self.prompt},
        ]

    def cache_key(self) -> str:
        return md5_hex(f"{self.model}::{self.name}::{json.dumps(self.messages(), ensure_ascii=False)}")


# ── Error classification ──────────────────────────────────────────────────

_UNAVAILABLE_STATUS = {401, 402, 403, 408, 429, 500, 502, 503, 504, 529}
_UNAVAILABLE_HINTS = (
    "usage limit", "rate limit", "limit reached", "hit your limit", "quota",
    "credit", "billing", "overloaded", "too many requests",
    "log in", "login", "logged out", "not logged", "authenticat", "unauthorized",
    "oauth", "invalid api key", "subscription",
    "network", "connection", "econnre", "enotfound", "etimedout", "fetch failed",
    "service unavailable", "internal server error", "bad gateway",
)


def _classify(message: str, status: int | None = None) -> AIError:
    low = message.lower()
    if status in _UNAVAILABLE_STATUS or (status or 0) >= 500:
        return AIUnavailable(message)
    if "schema" in low or "structured output" in low:
        return AIError(message)
    if any(h in low for h in _UNAVAILABLE_HINTS):
        return AIUnavailable(message)
    return AIError(message)


# ── Claude (text / JSON) ──────────────────────────────────────────────────


def _claude_code(task: Task) -> Any:
    """Run one task through ``claude -p`` (your Claude subscription)."""
    cfg = settings.ai
    cmd = [
        cfg.claude_cli, "-p",
        "--output-format", "json",
        "--no-session-persistence",
        "--tools", "",
        "--model", task.model,
        "--effort", cfg.effort,
        "--system-prompt", task.system,
    ]
    if task.schema is not None:
        cmd += ["--json-schema", json.dumps(task.schema)]
    try:
        proc = subprocess.run(
            cmd, input=task.prompt, capture_output=True, text=True,
            timeout=task.timeout or cfg.timeout,
            cwd=tempfile.gettempdir(),  # no project CLAUDE.md / settings
        )
    except FileNotFoundError as exc:
        raise AIError(f"Claude Code CLI not found ({cfg.claude_cli!r}); install it or set [ai] claude_cli") from exc
    except subprocess.TimeoutExpired as exc:
        raise AIError(f"{task.name}: no answer within {exc.timeout}s") from exc
    try:
        data = json.loads(proc.stdout)
    except json.JSONDecodeError:
        detail = (proc.stderr or proc.stdout or f"exit code {proc.returncode}").strip()
        raise _classify(f"claude -p failed: {detail[-400:]}")
    if data.get("is_error") or data.get("subtype") != "success":
        detail = str(data.get("result") or data.get("subtype") or "unknown error")
        raise _classify(f"claude -p: {detail[:400]}", data.get("api_error_status"))
    if task.schema is None:
        return (data.get("result") or "").strip()
    out = data.get("structured_output")
    if isinstance(out, dict):
        return out
    try:
        return json.loads(data.get("result") or "")
    except json.JSONDecodeError as exc:
        raise AIError(f"{task.name}: no structured output in Claude's answer") from exc


# ── Availability gate + concurrency ───────────────────────────────────────


class _Gate:
    """Pauses every caller while Claude is unavailable.

    The first caller to see an outage becomes the prober: it retries its own
    request every ``unavailable_retry_minutes`` and reopens the gate when it
    succeeds. Everyone else blocks until then, so an outage costs one retry
    per interval rather than one per worker.
    """

    def __init__(self, name: str = "Claude") -> None:
        self.name = name
        self.open = threading.Event()
        self.open.set()
        self.lock = threading.Lock()

    def call(self, fn: Callable[[], Any]) -> Any:
        while True:
            while not self.open.wait(timeout=1):
                if STOP.is_set():
                    raise AIError("interrupted")
            try:
                return fn()
            except AIUnavailable as exc:
                with self.lock:
                    prober = self.open.is_set()
                    if prober:
                        self.open.clear()
                if prober:
                    return self._probe(fn, exc)
                # someone else is probing — wait for the gate to reopen

    def _probe(self, fn: Callable[[], Any], exc: AIUnavailable) -> Any:
        interval = max(0.1, settings.ai.unavailable_retry_minutes) * 60
        until_reset = seconds_until_reset(str(exc))
        if until_reset and until_reset > interval:
            print(f"\n  ⏸  {self.name}: limit resets in {until_reset / 60:.0f} min — sleeping until then.", flush=True)
            if STOP.wait(until_reset):
                raise AIError(f"interrupted while waiting for {self.name}")
            try:
                result = fn()
                print(f"  ▶  {self.name} available again — resuming.", flush=True)
                self.open.set()
                return result
            except AIUnavailable as again:
                exc = again
        print(f"\n  ⏸  {self.name} unavailable: {exc}\n"
              f"     Pausing all AI work; retrying every {interval / 60:g} min "
              f"(Ctrl-C to stop).", flush=True)
        try:
            while True:
                nxt = datetime.now() + timedelta(seconds=interval)
                print(f"     next attempt at {nxt:%H:%M}", flush=True)
                if STOP.wait(interval):
                    raise AIError(f"interrupted while waiting for {self.name}")
                try:
                    result = fn()
                except AIUnavailable as again:
                    print(f"     still unavailable: {str(again)[:160]}", flush=True)
                    continue
                print(f"  ▶  {self.name} available again — resuming.", flush=True)
                return result
        finally:
            self.open.set()


_RESET = re.compile(r"resets?\s+(?:at\s+)?(\d{1,2})(?::(\d{2}))?\s*(am|pm)?", re.I)


def seconds_until_reset(message: str) -> float | None:
    """Seconds until a limit message's reset time ("resets 11:40pm"), + 2 min margin."""
    m = _RESET.search(message)
    if not m:
        return None
    hour, minute, ampm = int(m.group(1)), int(m.group(2) or 0), (m.group(3) or "").lower()
    if ampm == "pm" and hour != 12:
        hour += 12
    elif ampm == "am" and hour == 12:
        hour = 0
    if hour > 23 or minute > 59:
        return None
    now = datetime.now()
    target = now.replace(hour=hour, minute=minute, second=0, microsecond=0)
    if target <= now:
        target += timedelta(days=1)
    return (target - now).total_seconds() + 120


_gate = _Gate("Claude")
_slots = threading.BoundedSemaphore(max(1, settings.ai.concurrency))


def _call(task: Task) -> Any:
    def once() -> Any:
        with _slots:
            return _claude_code(task)

    return _gate.call(once)


# ── Client ────────────────────────────────────────────────────────────────


class AI:
    """AI client bound to a DB connection (for the cache).

    ``conn`` may be None for callers that never cache (e.g. practice).
    ``lock`` serialises cache access when the connection is shared by a
    thread pool.
    """

    def __init__(self, conn: sqlite3.Connection | None = None, lock: Any = None):
        self.conn = conn
        self.lock = lock or threading.Lock()

    def _cache_get(self, key: str) -> Any | None:
        if self.conn is None:
            return None
        with self.lock:
            row = self.conn.execute(
                "SELECT response_json FROM ai_cache WHERE cache_key = ?", (key,)
            ).fetchone()
        return json.loads(row[0]) if row else None

    def _cache_put(self, key: str, value: Any) -> None:
        if self.conn is None:
            return
        with self.lock:
            self.conn.execute(
                "INSERT OR REPLACE INTO ai_cache (cache_key, response_json) VALUES (?, ?)",
                (key, json.dumps(value, ensure_ascii=False)),
            )
            self.conn.commit()

    def run(self, task: Task, *, refresh: bool = False) -> Any:
        """Run one task. Structured tasks return a dict, others a string."""
        use_cache = task.cache and self.conn is not None
        key = task.cache_key() if use_cache else ""
        if use_cache and not refresh:
            hit = self._cache_get(key)
            if hit is not None:
                return hit
        result = _call(task)
        if use_cache:
            self._cache_put(key, result)
        return result

    def run_many(
        self,
        items: Iterable[T],
        make_task: Callable[[T], Task],
        *,
        workers: int,
        label: str,
        describe: Callable[[T], str] | None = None,
        refresh: bool = False,
        progress_every: int = 50,
    ) -> Iterator[tuple[T, Any]]:
        """Run a task per item in parallel; yields ``(item, result | Exception)``."""
        yield from run_pool(
            list(items),
            lambda item: self.run(make_task(item), refresh=refresh),
            workers=workers,
            label=label,
            describe=describe,
            progress_every=progress_every,
        )
