"""Central settings, loaded from ``settings.toml`` at the repo root.

Defaults live here; the TOML file overrides them. Unknown keys are an
error so a typo can't silently fall back to a default. Read settings with
``from .settings import settings`` — the object is loaded once per process.
"""

from __future__ import annotations

import os
import tomllib
import types
from typing import get_args, get_origin, get_type_hints
from dataclasses import dataclass, field, fields, is_dataclass, replace
from pathlib import Path

from .paths import PROJECT_ROOT


@dataclass(frozen=True)
class AISettings:
    """Text / JSON AI — always Claude, via `claude -p` on your subscription."""

    #: Claude Code model alias or name ("opus", "sonnet", …).
    model: str = "opus"
    #: Claude Code effort level: low | medium | high | xhigh | max.
    effort: str = "medium"
    #: Claude's hidden reasoning. Off: ~8x fewer output tokens and much faster
    #: (fine for the cheap pass); on: better judgement for the final quality pass.
    thinking: bool = False
    #: Seconds before one AI call is abandoned.
    timeout: int = 600
    #: Max AI calls in flight at once (each Claude Code call is a process).
    concurrency: int = 4
    #: While Claude is unavailable (usage limit, logged out, network down)
    #: all AI work pauses and retries this often.
    unavailable_retry_minutes: float = 5
    #: Claude Code executable.
    claude_cli: str = "claude"
    #: task name → model; see ``flashcards/tasks.py`` for task names.
    task_models: dict = field(default_factory=dict)
    #: 0 = wait for Claude/Codex to come back however long it takes.
    max_unavailable_minutes: float = 0
    task_version: str = "5"

    def model_for(self, task: str) -> str:
        return self.task_models.get(task, self.model)


@dataclass(frozen=True)
class FactSettings:
    enabled: bool = True
    #: Facts below this model-reported confidence are stored but not shown.
    min_confidence: float = 0.75


@dataclass(frozen=True)
class AudioSettings:
    voice_id: str = "HuK8QKF35exsCh2e7fLT"
    model: str = "eleven_multilingual_v2"
    format: str = "mp3_44100_128"
    language: str = "it"
    stability: float = 0.5
    similarity_boost: float = 1.0
    style: float = 1.0
    speed: float = 0.7
    compressed_bitrate: str = "48k"


@dataclass(frozen=True)
class ImageSettings:
    """Images: generated by Codex (ChatGPT plan), compressed for Anki."""

    codex_timeout: int = 900
    compressed_max_px: int = 512
    compressed_quality: int = 75
    #: Every card needs an image: notes wait for theirs before going to Anki.
    required: bool = True


@dataclass(frozen=True)
class RunSettings:
    audio_workers: int = 5
    compress_workers: int = 8
    #: New assets created per run: 0 = none, -1 = no limit (None after loading).
    #: ``image_limit = 0`` never starts Codex.
    image_limit: int | None = None
    audio_limit: int | None = None
    #: AI batches between Anki syncs in ``flashcards run``.
    max_batches: int = 20


@dataclass(frozen=True)
class AnkiSettings:
    url: str = "http://127.0.0.1:8765"
    profile: str = ""


@dataclass(frozen=True)
class BackupSettings:
    keep_last: int = 10
    mirror_dir: str = ""


@dataclass(frozen=True)
class AuditSettings:
    workers: int = 6
    block_failures: bool = True


@dataclass(frozen=True)
class PracticeSettings:
    words: int = 50
    sentences: int = 10
    length: str = "medium"
    no_subjunctive: bool = False


@dataclass(frozen=True)
class LeechSettings:
    threshold: int = 5
    relearn_steps: list = field(default_factory=lambda: [10])


@dataclass(frozen=True)
class Settings:
    ai: AISettings = field(default_factory=AISettings)
    facts: FactSettings = field(default_factory=FactSettings)
    audio: AudioSettings = field(default_factory=AudioSettings)
    images: ImageSettings = field(default_factory=ImageSettings)
    run: RunSettings = field(default_factory=RunSettings)
    anki: AnkiSettings = field(default_factory=AnkiSettings)
    backups: BackupSettings = field(default_factory=BackupSettings)
    audit: AuditSettings = field(default_factory=AuditSettings)
    practice: PracticeSettings = field(default_factory=PracticeSettings)
    leech: LeechSettings = field(default_factory=LeechSettings)


SETTINGS_PATH = Path(os.environ.get("FLASHCARDS_SETTINGS") or PROJECT_ROOT / "settings.toml")


def _merge(obj, data: dict, where: str):
    known = {f.name: f for f in fields(obj)}
    unknown = sorted(set(data) - set(known))
    if unknown:
        raise ValueError(f"{SETTINGS_PATH.name}: unknown key(s) in [{where}]: {unknown}")
    changes = {}
    for key, value in data.items():
        current = getattr(obj, key)
        if is_dataclass(current):
            if not isinstance(value, dict):
                raise ValueError(f"{SETTINGS_PATH.name}: [{where}.{key}] must be a table")
            changes[key] = _merge(current, value, f"{where}.{key}".strip("."))
        else:
            expected = get_type_hints(type(obj))[key]
            if not _matches(value, expected):
                raise ValueError(f"settings: {where}.{key} has wrong type (expected {expected})")
            changes[key] = value
    return replace(obj, **changes)


def _matches(value, typ):
    origin = get_origin(typ)
    if origin is types.UnionType:
        return any(_matches(value, t) for t in get_args(typ))
    if typ is float:
        return type(value) in (int, float)
    return type(value) is typ


def load(path: Path = SETTINGS_PATH) -> Settings:
    if not path.exists():
        return Settings()
    with path.open("rb") as fh:
        data = tomllib.load(fh)
    s = _merge(Settings(), data, "")
    for section, names in (
        (s.ai, ("timeout", "concurrency", "unavailable_retry_minutes")),
        (s.images, ("codex_timeout", "compressed_max_px")),
        (s.run, ("audio_workers", "compress_workers", "max_batches")),
        (s.backups, ("keep_last",)),
        (s.audit, ("workers",)),
        (s.practice, ("words", "sentences")),
        (s.leech, ("threshold",)),
    ):
        for name in names:
            if getattr(section, name) <= 0:
                raise ValueError(f"settings: {name} must be positive")
    if s.ai.max_unavailable_minutes < 0:
        raise ValueError("settings: max_unavailable_minutes must be 0 (no limit) or positive")
    for value in (
        s.facts.min_confidence,
        s.audio.stability,
        s.audio.similarity_boost,
        s.audio.style,
    ):
        if not 0 <= value <= 1:
            raise ValueError("settings: confidence/ratio/voice controls must be between 0 and 1")
    if not 1 <= s.images.compressed_quality <= 95:
        raise ValueError("settings: invalid image quality")
    if not 0.5 <= s.audio.speed <= 2 or s.ai.effort not in {"low", "medium", "high", "xhigh", "max"}:
        raise ValueError("settings: invalid audio speed or AI effort")
    if any(not isinstance(k, str) or not isinstance(v, str) for k, v in s.ai.task_models.items()):
        raise ValueError("settings: task_models must map task names to model strings")
    # TOML has no null: a negative asset limit means "no limit".
    return replace(
        s,
        run=replace(
            s.run, image_limit=asset_limit(s.run.image_limit), audio_limit=asset_limit(s.run.audio_limit)
        ),
    )


def asset_limit(value: int | None) -> int | None:
    """0 = create none, n = at most n, negative / None = no limit."""
    return None if value is None or value < 0 else value


settings = load()
