#!/usr/bin/env python3
"""Create card_items for italki entries.

Handles two word_types:

1. italki_verb  (imported by 04_italki_import_verbs.py,
                 forms generated by 06_italki_create_verb_forms.py)
   - One card_item per verb_form row → tense-specific italki deck
   - One card_item per verb entry (infinitive) → "Italian - Italki Verbs Infinitive"

2. italki_expression  (imported by 05_italki_import_expressions.py)
   - One card_item per entry → "Italian - Italki"

Italki verb decks:
  Italian - Italki Verbs Presente
  Italian - Italki Verbs Passato Prossimo
  Italian - Italki Verbs Imperfetto
  Italian - Italki Verbs Imperativo
  Italian - Italki Verbs Infinitive

Expression deck:
  Italian - Italki
"""

from __future__ import annotations

import argparse
import sqlite3
from pathlib import Path

from common import DEFAULT_DB_PATH

PROJECT_ROOT = Path(__file__).resolve().parents[1]

ITALKI_EXPRESSION_DECK = "Italian - Italki"

ITALKI_VERB_INFINITIVE_DECK = "Italian - Italki Verbs Infinitive"

ITALKI_TENSE_TO_DECK: dict[str, str] = {
    "presente":         "Italian - Italki Verbs Presente",
    "passato_prossimo": "Italian - Italki Verbs Passato Prossimo",
    "imperfetto":       "Italian - Italki Verbs Imperfetto",
    "imperativo":       "Italian - Italki Verbs Imperativo",
}


# ---------------------------------------------------------------------------
# italki_expression card items
# ---------------------------------------------------------------------------

def create_expression_card_items(connection: sqlite3.Connection) -> int:
    """One card_item per italki_expression entry, in the Italian - Italki deck."""
    rows = connection.execute(
        """
        SELECT we.id AS word_entry_id, we.lemma, we.english
        FROM word_entries we
        WHERE we.word_type = 'italki_expression'
          AND NOT EXISTS (
              SELECT 1 FROM card_items ci
              WHERE ci.source_type = 'italki_expression' AND ci.source_id = we.id
          )
        ORDER BY we.lemma
        """
    ).fetchall()

    inserted = 0
    for row in rows:
        cursor = connection.execute(
            """
            INSERT INTO card_items (
                source_type, source_id, natural_key,
                deck, front_text, front_labels,
                back_highlight, back_text, audio_text, image_text
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                "italki_expression",
                row["word_entry_id"],
                f"italki_expression:{row['word_entry_id']}",
                ITALKI_EXPRESSION_DECK,
                row["english"],           # front: English prompt
                "source: italki",         # label pill
                row["lemma"],             # back_highlight: Italian answer
                None,                     # back_text
                row["lemma"],             # audio_text
                row["lemma"],             # image_text (allow image generation)
            ),
        )
        inserted += cursor.rowcount
    return inserted


# ---------------------------------------------------------------------------
# italki_verb infinitive card items
# ---------------------------------------------------------------------------

def create_italki_verb_infinitive_card_items(connection: sqlite3.Connection) -> int:
    """One infinitive card_item per italki_verb entry."""
    rows = connection.execute(
        """
        SELECT we.id AS word_entry_id, we.infinitive, we.english
        FROM word_entries we
        WHERE we.word_type = 'italki_verb'
          AND NOT EXISTS (
              SELECT 1 FROM card_items ci
              WHERE ci.source_type = 'italki_infinitive_verb' AND ci.source_id = we.id
          )
        ORDER BY we.lemma
        """
    ).fetchall()

    inserted = 0
    for row in rows:
        cursor = connection.execute(
            """
            INSERT INTO card_items (
                source_type, source_id, natural_key,
                deck, front_text, front_labels,
                back_highlight, back_text, audio_text, image_text
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                "italki_infinitive_verb",
                row["word_entry_id"],
                f"italki_infinitive_verb:{row['word_entry_id']}",
                ITALKI_VERB_INFINITIVE_DECK,
                row["english"],
                "tense: infinitive | source: italki",
                row["infinitive"],
                None,
                row["infinitive"],
                row["infinitive"],
            ),
        )
        inserted += cursor.rowcount
    return inserted


# ---------------------------------------------------------------------------
# italki_verb conjugated form card items
# ---------------------------------------------------------------------------

def create_italki_verb_form_card_items(connection: sqlite3.Connection) -> int:
    """One card_item per verb_form row belonging to an italki_verb entry."""
    rows = connection.execute(
        """
        SELECT
            vf.id        AS vf_id,
            vf.word_entry_id,
            vf.tense,
            vf.person,
            vf.polarity,
            vf.italian,
            vf.english,
            vf.labels,
            we.infinitive
        FROM verb_forms vf
        JOIN word_entries we ON vf.word_entry_id = we.id
        WHERE we.word_type = 'italki_verb'
          AND NOT EXISTS (
              SELECT 1 FROM card_items ci
              WHERE ci.source_type = 'italki_verb_form' AND ci.source_id = vf.id
          )
        ORDER BY we.lemma, vf.tense, vf.person
        """
    ).fetchall()

    inserted = 0
    for row in rows:
        deck = ITALKI_TENSE_TO_DECK.get(row["tense"], f"Italian - Italki Verbs {row['tense']}")
        natural_key = (
            f"italki_verb_form:{row['word_entry_id']}"
            f":{row['tense']}:{row['person']}:{row['polarity']}"
        )
        # Append source label to existing tense/subject labels
        labels = row["labels"] or ""
        if labels:
            labels = f"{labels} | source: italki"
        else:
            labels = "source: italki"

        cursor = connection.execute(
            """
            INSERT INTO card_items (
                source_type, source_id, natural_key,
                deck, front_text, front_labels,
                back_highlight, back_text, audio_text, image_text
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                "italki_verb_form",
                row["vf_id"],
                natural_key,
                deck,
                row["english"],       # front: English prompt
                labels,
                row["italian"],       # back_highlight: Italian conjugated form
                row["infinitive"],    # back_text: infinitive for context
                row["italian"],       # audio_text
                row["infinitive"],    # image_text keyed on infinitive
            ),
        )
        inserted += cursor.rowcount
    return inserted


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def print_banner() -> None:
    title = "14 Italki create card_items"
    line = "-" * len(title)
    print(f"\n{line}\n{title}\n{line}", flush=True)


def main() -> None:
    print_banner()
    parser = argparse.ArgumentParser(
        description="Create card_items for italki_verb and italki_expression entries."
    )
    parser.add_argument("--db", type=Path, default=DEFAULT_DB_PATH)
    args = parser.parse_args()

    with sqlite3.connect(args.db, timeout=30) as connection:
        connection.row_factory = sqlite3.Row
        connection.execute("PRAGMA foreign_keys = ON")

        # Pre-flight counts
        expression_count = connection.execute(
            "SELECT COUNT(*) AS c FROM word_entries WHERE word_type = 'italki_expression'"
        ).fetchone()["c"]
        italki_verb_count = connection.execute(
            "SELECT COUNT(*) AS c FROM word_entries WHERE word_type = 'italki_verb'"
        ).fetchone()["c"]
        italki_verb_form_count = connection.execute(
            """
            SELECT COUNT(*) AS c FROM verb_forms vf
            JOIN word_entries we ON vf.word_entry_id = we.id
            WHERE we.word_type = 'italki_verb'
            """
        ).fetchone()["c"]

        print(f"  italki_expression entries:  {expression_count}")
        print(f"  italki_verb entries:        {italki_verb_count}")
        print(f"  italki_verb verb_forms:     {italki_verb_form_count}")

        if expression_count == 0 and italki_verb_count == 0:
            print("No italki entries found. Run scripts 04 and 05 first.")
            return

        expr_inserted = create_expression_card_items(connection)
        inf_inserted = create_italki_verb_infinitive_card_items(connection)
        form_inserted = create_italki_verb_form_card_items(connection)
        connection.commit()

    total = expr_inserted + inf_inserted + form_inserted
    print(f"\n  Inserted {expr_inserted} italki_expression card_items → '{ITALKI_EXPRESSION_DECK}'")
    print(f"  Inserted {inf_inserted} italki infinitive card_items → '{ITALKI_VERB_INFINITIVE_DECK}'")
    for tense, deck in ITALKI_TENSE_TO_DECK.items():
        print(f"  (verb form cards for '{deck}' included in {form_inserted} total)")
    print(f"\nTotal inserted: {total} card_items.")


if __name__ == "__main__":
    main()
